# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Driver.destroy_all

Driver.create!([{
    url: "https://i.ibb.co/KhWv9T0/perfil-charles-leclerc-2022-soymotor.png",
    id: "1",
    nombre: "Charles Leclerc",
    grupo: "2B",
    adelantamiento: "27",
    consistencia: "35",
    defender: "29",
    gestion_combustible: "37",
    gestion_neumaticos: "42",
    capacidad_clima_humeda: "28",
    total: "198",
    equipo: "ferrari"
},
{
    url: "https://i.ibb.co/QY2pVcf/carlos-sainz-jr-ferrari-1.jpg",
    id: "2",
    nombre: "Carlos Sainz",
    grupo: "2C",
    adelantamiento: "23",
    consistencia: "31",
    defender: "34",
    gestion_combustible: "33",
    gestion_neumaticos: "33",
    capacidad_clima_humeda: "31",
    total: "185",
    equipo: "ferrari"
},
{
    url: "https://i.ibb.co/BsPFV6P/perfil-valtteri-bottas-2022-soymotor.png",
    id: "3",
    nombre: "Valtteri Bottas",
    grupo: "1A",
    adelantamiento: "21",
    consistencia: "18",
    defender: "29",
    gestion_combustible: "25",
    gestion_neumaticos: "31",
    capacidad_clima_humeda: "16",
    total: "140",
    equipo: "Alfa Romeo"
},
{
    url: "https://i.ibb.co/W2W92hq/guanyu-zhou-alfa-romeo-1.jpg",
    id: "4",
    nombre: "Guanyo Zhou",
    grupo: "1B",
    adelantamiento: "8",
    consistencia: "8",
    defender: "6",
    gestion_combustible: "10",
    gestion_neumaticos: "8",
    capacidad_clima_humeda: "2",
    total: "42",
    equipo: "Alfa Romeo"
},
{
    url: "https://i.ibb.co/cFJ0Sdk/descarga.jpg",
    id: "5",
    nombre: "Fernando Alonso",
    grupo: "1C",
    adelantamiento: "31",
    consistencia: "28",
    defender: "32",
    gestion_combustible: "36",
    gestion_neumaticos: "30",
    capacidad_clima_humeda: "23",
    total: "180",
    equipo: "Alpine"
},
{
    url: "https://i.ibb.co/G0M008T/esteban-ocon-alpine-1.jpg",
    id: "6",
    nombre: "Esteban Ocon",
    grupo: "1D",
    adelantamiento: "19",
    consistencia: "33",
    defender: "30",
    gestion_combustible: "34",
    gestion_neumaticos: "32",
    capacidad_clima_humeda: "21",
    total: "158",
    equipo: "Alpine"
},
{
    url: "https://i.ibb.co/jf8zJLG/pierre-gasly-alphatauri-1.jpg",
    id: "7",
    nombre: "Pierre Gasly",
    grupo: "1E",
    adelantamiento: "28",
    consistencia: "26",
    defender: "36",
    gestion_combustible: "32",
    gestion_neumaticos: "38",
    capacidad_clima_humeda: "22",
    total: "182",
    equipo: "Alpha Tauri"
},
{
    url: "https://i.ibb.co/KXYBfHS/yuki-tsunoda-alphatauri-1.jpg",
    id: "8",
    nombre: "Yuki Tsunoda",
    grupo: "1F",
    adelantamiento: "19",
    consistencia: "23",
    defender: "20",
    gestion_combustible: "23",
    gestion_neumaticos: "22",
    capacidad_clima_humeda: "11",
    total: "118",
    equipo: "Alpha Tauri"
},
{
    url: "https://i.ibb.co/BtGkMq3/sebastian-vettel-aston-martin-1.jpg",
    id: "9",
    nombre: "Sebastian Vettel",
    grupo: "1G",
    adelantamiento: "26",
    consistencia: "26",
    defender: "27",
    gestion_combustible: "27",
    gestion_neumaticos: "27",
    capacidad_clima_humeda: "27",
    total: "160",
    equipo: "Aston Martin F1"
},
{
    url: "https://i.ibb.co/VggJq6J/lance-stroll-aston-martin-1.jpg",
    id: "10",
    nombre: "Lance Stroll",
    grupo: "1H",
    adelantamiento: "24",
    consistencia: "21",
    defender: "25",
    gestion_combustible: "23",
    gestion_neumaticos: "23",
    capacidad_clima_humeda: "22",
    total: "138",
    equipo: "Aston Martin F1"
},
{
    url: "https://i.ibb.co/QpDdmyT/perfil-kevin-magnussen-2022-soymotor-1-1.png",
    id: "11",
    nombre: "Kevin Magnussen",
    grupo: "2A",
    adelantamiento: "7",
    consistencia: "4",
    defender: "15",
    gestion_combustible: "15",
    gestion_neumaticos: "14",
    capacidad_clima_humeda: "3",
    total: "58",
    equipo: "Hass"
},
{
    url: "https://i.ibb.co/VTv4WMW/mick-schumacher-haas-f1-team-1.jpg",
    id: "12",
    nombre: "Mick Schumacher",
    grupo: "2D",
    adelantamiento: "10",
    consistencia: "2",
    defender: "7",
    gestion_combustible: "4",
    gestion_neumaticos: "2",
    capacidad_clima_humeda: "9",
    total: "34",
    equipo: "Hass"
},
{    
    url: "https://i.ibb.co/w6dX5xM/lando-norris-mclaren-1.jpg",
    id: "13",
    nombre: "Lando Norris",
    grupo: "2E",
    adelantamiento: "30",
    consistencia: "28",
    defender: "32",
    gestion_combustible: "41",
    gestion_neumaticos: "39",
    capacidad_clima_humeda: "32",
    total: "202",
    equipo: "Mclaren F1"
},
{
    url: "https://i.ibb.co/WvZTgLb/daniel-ricciardo-mclaren-1.jpg",
    id: "14",
    nombre: "Daniel Ricciardo",
    grupo: "2F",
    adelantamiento: "21",
    consistencia: "25",
    defender: "23",
    gestion_combustible: "33",
    gestion_neumaticos: "37",
    capacidad_clima_humeda: "24",
    total: "163",
    equipo: "Mclaren F1"
},
{
    url: "https://i.ibb.co/2Njp0w9/lewis-hamilton-mercedes-1.jpg",
    id: "15",
    nombre: "Lewis Hamilton",
    grupo: "2G",
    adelantamiento: "32",
    consistencia: "38",
    defender: "36",
    gestion_combustible: "33",
    gestion_neumaticos: "36",
    capacidad_clima_humeda: "28",
    total: "207",
    equipo: "Mercedes Benz F1"
},
{
    url: "https://i.ibb.co/p1D19f8/george-russell-mercedes-1.jpg",
    id: "16",
    nombre: "George Russel",
    grupo: "2H",
    adelantamiento: "33",
    consistencia: "31",
    defender: "39",
    gestion_combustible: "32",
    gestion_neumaticos: "37",
    capacidad_clima_humeda: "30",
    total: "202",
    equipo: "Mercedes Benz F1"
},
{
    url: "https://i.ibb.co/c1PsMBP/max-verstappen-red-bull-racing-1.jpg",
    id: "17",
    nombre: "Max Verstappen",
    grupo: "3A",
    adelantamiento: "36",
    consistencia: "32",
    defender: "36",
    gestion_combustible: "34",
    gestion_neumaticos: "42",
    capacidad_clima_humeda: "25",
    total: "205",
    equipo: "RedBull F1"
},
{
    url: "https://i.ibb.co/9NGZcYf/sergio-perez-red-bull-racing-1-1.jpg",
    id: "18",
    nombre: "Sergio Perez",
    grupo: "3B",
    adelantamiento: "26",
    consistencia: "33",
    defender: "28",
    gestion_combustible: "28",
    gestion_neumaticos: "35",
    capacidad_clima_humeda: "28",
    total: "178",
    equipo: "RedBull F1"
},
{
    url: "https://i.ibb.co/bBPc57K/Nicholas-Latifi.jpg",
    id: "19",
    nombre: "Nicholas Latifi",
    grupo: "",
    adelantamiento: "9",
    consistencia: "17",
    defender: "14",
    gestion_combustible: "18",
    gestion_neumaticos: "24",
    capacidad_clima_humeda: "17",
    total: "98",
    equipo: "Williams F1"
},
{
    url:"https://i.ibb.co/xY6Tq7j/alex-albon-williams-racing-1.jpg",
    id: "20",
    nombre: "Alex Albon",
    grupo: "",
    adelantamiento: "9",
    consistencia: "7",
    defender: "17",
    gestion_combustible: "13",
    gestion_neumaticos: "22",
    capacidad_clima_humeda: "10",
    total: "78",
    equipo: "Williams F1"
},
])